import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

// Read sources
const csvText = readFileSync(resolve(root, "..", "companies_raw.csv"), "utf-8");
const mdText = readFileSync(resolve(root, "..", "topics.md"), "utf-8");

// Parse topics.md — extract sections and topics
const sections = [];
const topicMap = new Map(); // id -> { name, sectionId }
let currentSectionId = null;

for (const line of mdText.split("\n")) {
  const sectionMatch = line.match(/^## (\d+)\.\s+(.+)/);
  if (sectionMatch) {
    currentSectionId = parseInt(sectionMatch[1]);
    sections.push({ id: currentSectionId, name: sectionMatch[2].trim() });
    continue;
  }
  const topicMatch = line.match(/^(\d+)\.\s+(.+)/);
  if (topicMatch && currentSectionId !== null) {
    const id = parseInt(topicMatch[1]);
    topicMap.set(id, { name: topicMatch[2].trim(), sectionId: currentSectionId });
  }
}

// Parse CSV — group companies by topic_id
const companiesByTopic = new Map();
const csvLines = csvText.trim().split("\n");
for (let i = 1; i < csvLines.length; i++) {
  const parts = csvLines[i].split("|");
  if (parts.length < 4) continue;
  const topicId = parseInt(parts[0]);
  const company = parts[2].trim();
  const url = parts[3].trim();
  if (!companiesByTopic.has(topicId)) companiesByTopic.set(topicId, []);
  companiesByTopic.get(topicId).push({ name: company, url });
}

// Build topics array — only topics from topics.md
const topics = [];
for (const [id, { name, sectionId }] of topicMap) {
  topics.push({
    id,
    name,
    sectionId,
    companies: companiesByTopic.get(id) || [],
  });
}
topics.sort((a, b) => a.id - b.id);

// Log CSV topic_ids not found in topics.md
for (const tid of companiesByTopic.keys()) {
  if (!topicMap.has(tid)) {
    console.warn(`Warning: topic_id ${tid} in CSV not found in topics.md — skipped`);
  }
}

// Generate output
const out = `// Auto-generated by scripts/generate-data.js — do not edit manually
export const sections = ${JSON.stringify(sections, null, 2)};

export const topics = ${JSON.stringify(topics, null, 2)};
`;

const outPath = resolve(root, "src", "data", "topics.js");
writeFileSync(outPath, out, "utf-8");
console.log(`Written ${outPath}`);
console.log(`  ${sections.length} sections, ${topics.length} topics, ${csvLines.length - 1} CSV rows`);
