const fs = require('fs');
const path = require('path');

const reportsDir = path.join(__dirname, '..', 'src', 'data', 'reports');
const outputFile = path.join(__dirname, '..', 'src', 'data', 'reports.js');

const files = fs.readdirSync(reportsDir).filter(f => f.endsWith('.json'));

const reports = {};
let count = 0;

for (const file of files) {
  try {
    const data = JSON.parse(fs.readFileSync(path.join(reportsDir, file), 'utf8'));
    reports[data.topicId] = data;
    count++;
  } catch (e) {
    console.error(`Error parsing ${file}: ${e.message}`);
  }
}

const output = `// Auto-generated by merge-reports.js — do not edit manually
export const reports = ${JSON.stringify(reports, null, 2)};
`;

fs.writeFileSync(outputFile, output, 'utf8');
console.log(`Merged ${count} reports into ${outputFile}`);
